"""Initial migration

Revision ID: 98b4f058a8ae
Revises: 
Create Date: 2025-12-07 09:41:22.619863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b4f058a8ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('AWAITING_APPROVAL', 'PENDING', 'PAYMENT_PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'FAILED', name='orderstatus'), nullable=False),
    sa.Column('shipping_address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_order_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('idx_order_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_product_id'), 'orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('product_seller_cache',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index('idx_product_seller_cache_seller', 'product_seller_cache', ['seller_id'], unique=False)
    op.create_index(op.f('ix_product_seller_cache_product_id'), 'product_seller_cache', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_seller_cache_seller_id'), 'product_seller_cache', ['seller_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_seller_cache_seller_id'), table_name='product_seller_cache')
    op.drop_index(op.f('ix_product_seller_cache_product_id'), table_name='product_seller_cache')
    op.drop_index('idx_product_seller_cache_seller', table_name='product_seller_cache')
    op.drop_table('product_seller_cache')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_product_id'), table_name='orders')
    op.drop_index('idx_order_user_status', table_name='orders')
    op.drop_index('idx_order_created_at', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
